import { useEffect, useState, type ReactNode } from 'react'
import { Sidebar } from './Sidebar'
import type { User } from './features/meeting/meetingApi'
import { resetPreferences, type FontSizePreference, type Preferences, type ThemePreference } from './preferences'

type SettingsPageProps = { user: User; theme: 'light' | 'dark'; path: string; onNavigate: (path: string) => void; onToggleTheme: () => void; onLogout: () => void; preferences: Preferences; onPreferencesChange: (changes: Partial<Preferences>) => void }

function SettingRow({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <div className="settings-row"><div><strong>{title}</strong><span>{description}</span></div><div className="settings-control">{children}</div></div> }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="settings-toggle"><span>{label}</span><input aria-label={label} type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span className="settings-switch" aria-hidden="true" /></label> }
function Unsupported({ children }: { children: ReactNode }) { return <span className="settings-unsupported">Unsupported: {children}</span> }

export function SettingsPage({ user, theme, path, onNavigate, onToggleTheme, onLogout, preferences, onPreferencesChange }: SettingsPageProps) {
  const [activeSection, setActiveSection] = useState('appearance')
  const [devices, setDevices] = useState<MediaDeviceInfo[]>([])
  const [deviceMessage, setDeviceMessage] = useState('')
  useEffect(() => {
    if (!navigator.mediaDevices?.enumerateDevices) { setDeviceMessage('Device selection is unavailable in this browser.'); return }
    const refresh = async () => { try { setDevices(await navigator.mediaDevices.enumerateDevices()); setDeviceMessage('') } catch { setDeviceMessage('Device access was denied. Choose devices in the browser prompt during a meeting.') } }
    void refresh(); navigator.mediaDevices.addEventListener('devicechange', refresh); return () => navigator.mediaDevices.removeEventListener('devicechange', refresh)
  }, [])
  const microphones = devices.filter((device) => device.kind === 'audioinput')
  const speakers = devices.filter((device) => device.kind === 'audiooutput')
  const cameras = devices.filter((device) => device.kind === 'videoinput')
  const sections = ['account', 'appearance', 'audio', 'video', 'meeting', 'privacy', 'accessibility']
  const select = (label: string, value: string, options: Array<{ value: string; label: string }>, onChange: (value: string) => void, disabled = false) => <select aria-label={label} value={value} disabled={disabled} onChange={(event) => onChange(event.target.value)}><option value="">Default</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select>
  return <main className="app-shell" data-theme={theme}><div className="dashboard-shell"><Sidebar path={path} onNavigate={onNavigate}><div className="sidebar-card"><p className="eyebrow">Account</p><strong>{user.username}</strong><span>Your session is secured by the existing account service.</span></div></Sidebar><div className="main-panel"><header className="app-header"><div className="header-group"><p className="eyebrow">Workspace preferences</p><h2>Settings</h2></div><div className="header-user"><button type="button" className="theme-toggle" onClick={onToggleTheme}>{theme === 'dark' ? 'Light mode' : 'Dark mode'}</button><span>{user.username}</span><button type="button" className="button-quiet" onClick={onLogout}>Log out</button></div></header><div className="settings-content settings-workspace"><aside className="settings-navigation" aria-label="Settings categories">{sections.map((section) => <button type="button" key={section} className={activeSection === section ? 'settings-nav-active' : ''} onClick={() => { setActiveSection(section); document.getElementById(`settings-${section}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' }) }}>{section}</button>)}</aside><div className="settings-sections"><div className="settings-heading"><p className="eyebrow">Your workspace</p><h1>Settings</h1><p>Personal controls apply to this browser. Meeting controls require backend support and are clearly marked below.</p></div>
  <section className="settings-group" id="settings-account"><h2>Account</h2><SettingRow title="Name" description="Your authenticated account name."><span className="settings-value">{user.full_name || user.username}</span></SettingRow><SettingRow title="Email" description="Account email is read-only because no email-change API is available."><span className="settings-value">{user.email}</span></SettingRow></section>
  <section className="settings-group" id="settings-appearance"><h2>Appearance</h2><SettingRow title="Theme" description="Applied across the application and persisted on this device."><div className="theme-options">{(['light', 'dark', 'system'] as ThemePreference[]).map((option) => <button type="button" key={option} className={preferences.theme === option ? 'theme-choice theme-choice-active' : 'theme-choice'} onClick={() => onPreferencesChange({ theme: option })}>{option[0].toUpperCase() + option.slice(1)}</button>)}</div></SettingRow><SettingRow title="Reduce motion" description="Removes non-essential transitions and animation."><Toggle label="Reduce motion" checked={preferences.reduceMotion} onChange={(checked) => onPreferencesChange({ reduceMotion: checked })} /></SettingRow></section>
  <section className="settings-group" id="settings-audio"><h2>Audio</h2><SettingRow title="Microphone" description="Used by the existing LiveKit meeting session.">{select('Microphone device', preferences.microphoneDeviceId, microphones.map((device) => ({ value: device.deviceId, label: device.label || 'Microphone' })), (value) => onPreferencesChange({ microphoneDeviceId: value }))}</SettingRow><SettingRow title="Speaker" description="Output switching uses setSinkId when the browser supports it.">{select('Speaker device', preferences.speakerDeviceId, speakers.map((device) => ({ value: device.deviceId, label: device.label || 'Speaker' })), (value) => onPreferencesChange({ speakerDeviceId: value }), !('setSinkId' in HTMLMediaElement.prototype))}</SettingRow>{deviceMessage && <p className="settings-note" role="status">{deviceMessage}</p>}<SettingRow title="Noise suppression" description="The current LiveKit audio pipeline does not expose a controllable processing setting."><Unsupported>noise suppression is not available in the current audio pipeline.</Unsupported></SettingRow><SettingRow title="Mute on entry" description="Starts the LiveKit microphone disabled when you join."><Toggle label="Mute on entry" checked={preferences.muteOnEntry} onChange={(checked) => onPreferencesChange({ muteOnEntry: checked })} /></SettingRow></section>
  <section className="settings-group" id="settings-video"><h2>Video</h2><SettingRow title="Camera" description="Used by the existing LiveKit meeting session.">{select('Camera device', preferences.cameraDeviceId, cameras.map((device) => ({ value: device.deviceId, label: device.label || 'Camera' })), (value) => onPreferencesChange({ cameraDeviceId: value }))}</SettingRow><SettingRow title="HD video" description="Adaptive LiveKit quality is enabled; a user quality override is not exposed by this room configuration."><Unsupported>HD quality override</Unsupported></SettingRow><SettingRow title="Mirror video" description="Mirrors only your local self-view, never remote participants."><Toggle label="Mirror video" checked={preferences.mirrorVideo} onChange={(checked) => onPreferencesChange({ mirrorVideo: checked })} /></SettingRow><SettingRow title="Camera on entry" description="Starts the camera only when explicitly enabled and permitted by the browser."><Toggle label="Camera on entry" checked={preferences.cameraOnEntry} onChange={(checked) => onPreferencesChange({ cameraOnEntry: checked })} /></SettingRow></section>
  <section className="settings-group" id="settings-meeting"><h2>Meeting</h2><SettingRow title="Waiting room" description="Requires server-side join state and host admission controls."><Unsupported>waiting room</Unsupported></SettingRow><SettingRow title="Join before host" description="Requires server-side authorization changes."><Unsupported>join before host</Unsupported></SettingRow><SettingRow title="Participant permissions" description="The current API exposes host moderation, not persistent capability policies."><Unsupported>participant permissions</Unsupported></SettingRow><SettingRow title="Screen sharing" description="LiveKit screen sharing is available, but host-only policy enforcement is not implemented."><Unsupported>sharing policy</Unsupported></SettingRow></section>
  <section className="settings-group" id="settings-privacy"><h2>Privacy</h2><SettingRow title="Visual engagement" description="Consent is explicit; processing stays local and only score/status metrics are submitted."><Toggle label="Visual engagement consent" checked={preferences.visualEngagementConsent} onChange={(checked) => onPreferencesChange({ visualEngagementConsent: checked })} /></SettingRow><SettingRow title="Voice moderation" description="Consent controls whether the existing one-response speech check may be used in a meeting."><Toggle label="Voice moderation consent" checked={preferences.voiceModerationConsent} onChange={(checked) => onPreferencesChange({ voiceModerationConsent: checked })} /></SettingRow></section>
  <section className="settings-group" id="settings-accessibility"><h2>Accessibility</h2><SettingRow title="High contrast" description="Uses stronger semantic contrast colors across the app."><Toggle label="High contrast" checked={preferences.highContrast} onChange={(checked) => onPreferencesChange({ highContrast: checked })} /></SettingRow><SettingRow title="Font size" description="Scales the application interface without changing stored account data.">{select('Font size', preferences.fontSize, (['small', 'default', 'large', 'extra-large'] as FontSizePreference[]).map((value) => ({ value, label: value.replace('-', ' ') })), (value) => onPreferencesChange({ fontSize: value as FontSizePreference }))}</SettingRow><SettingRow title="Reduce motion" description="The same canonical preference exposed under Appearance."><Toggle label="Reduce motion" checked={preferences.reduceMotion} onChange={(checked) => onPreferencesChange({ reduceMotion: checked })} /></SettingRow><button type="button" className="button-quiet settings-reset" onClick={() => onPreferencesChange(resetPreferences())}>Reset personal preferences</button></section>
</div></div></div></div></main>
}